"""added 2 columns to cartitem

Revision ID: 011217f8bdb6
Revises: 8dacdf429d0a
Create Date: 2024-11-23 16:58:22.523775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011217f8bdb6'
down_revision = '8dacdf429d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('variation_price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('variation_price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
