"""Update order and payment models

Revision ID: 07b7bd3c6b15
Revises: dbd93438886e
Create Date: 2025-05-13 22:39:44.681957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07b7bd3c6b15'
down_revision = 'dbd93438886e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('street', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('state')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['order_reference'])
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['id'])
        batch_op.create_foreign_key(None, 'payments', ['payment_id'], ['id'])
        batch_op.drop_column('address')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('date')
        batch_op.drop_column('payment')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_reference', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('payments_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payments_order_id_fkey', 'orders', ['order_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('mpesa_receipt')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('order_reference')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('address_id')
        batch_op.drop_column('order_reference')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('is_default')
        batch_op.drop_column('additional_info')
        batch_op.drop_column('street')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
