"""Add variation_name to order_items

Revision ID: 14136b0711ff
Revises: 29e82569ed76
Create Date: 2024-12-18 13:02:03.101895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14136b0711ff'
down_revision = '29e82569ed76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variation_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('variation_name')

    # ### end Alembic commands ###
