"""Added fields to Tablet model

Revision ID: 1d9fae4918bd
Revises: 8a692e7a3c66
Create Date: 2024-10-18 13:38:24.637594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9fae4918bd'
down_revision = '8a692e7a3c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_camera', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('front_camera', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('connectivity', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('colors', sa.String(length=100), nullable=False))
        batch_op.alter_column('ram',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('storage',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('battery',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('os',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.alter_column('os',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('battery',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('storage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('ram',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('colors')
        batch_op.drop_column('connectivity')
        batch_op.drop_column('front_camera')
        batch_op.drop_column('main_camera')

    # ### end Alembic commands ###
