"""added columns to Order table

Revision ID: 29e82569ed76
Revises: 011217f8bdb6
Create Date: 2024-12-17 20:01:12.824178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e82569ed76'
down_revision = '011217f8bdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('payment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('payment')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('address')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
