"""created audio laptop

Revision ID: 2a334e445493
Revises: d187e04aa466
Create Date: 2024-09-18 14:11:36.441389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a334e445493'
down_revision = 'd187e04aa466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('battery', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('ram', sa.String(length=20), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('battery', sa.String(length=50), nullable=False),
    sa.Column('display', sa.String(length=100), nullable=False),
    sa.Column('processor', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_urls', sa.Text(), nullable=False),
    sa.Column('ram', sa.String(length=20), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('battery', sa.String(length=50), nullable=False),
    sa.Column('main_camera', sa.String(length=100), nullable=False),
    sa.Column('front_camera', sa.String(length=100), nullable=False),
    sa.Column('display', sa.String(length=100), nullable=False),
    sa.Column('processor', sa.String(length=100), nullable=False),
    sa.Column('connectivity', sa.String(length=100), nullable=False),
    sa.Column('colors', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tablets_id', sa.Integer(), nullable=True))
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tablet', ['tablets_id'], ['id'])
        batch_op.create_foreign_key(None, 'laptop', ['laptop_id'], ['id'])
        batch_op.create_foreign_key(None, 'audio', ['audio_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tablets_id', sa.Integer(), nullable=True))
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'laptop', ['laptop_id'], ['id'])
        batch_op.create_foreign_key(None, 'audio', ['audio_id'], ['id'])
        batch_op.create_foreign_key(None, 'tablet', ['tablets_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tablets_id', sa.Integer(), nullable=True))
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'laptop', ['laptop_id'], ['id'])
        batch_op.create_foreign_key(None, 'tablet', ['tablets_id'], ['id'])
        batch_op.create_foreign_key(None, 'audio', ['audio_id'], ['id'])

    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tablets_id', sa.Integer(), nullable=True))
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tablet', ['tablets_id'], ['id'])
        batch_op.create_foreign_key(None, 'audio', ['audio_id'], ['id'])
        batch_op.create_foreign_key(None, 'laptop', ['laptop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tablets_id')
        batch_op.drop_column('audio_id')
        batch_op.drop_column('laptop_id')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tablets_id')
        batch_op.drop_column('audio_id')
        batch_op.drop_column('laptop_id')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tablets_id')
        batch_op.drop_column('audio_id')
        batch_op.drop_column('laptop_id')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('phone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tablets_id')
        batch_op.drop_column('audio_id')
        batch_op.drop_column('laptop_id')

    op.drop_table('tablet')
    op.drop_table('laptop')
    op.drop_table('audio')
    # ### end Alembic commands ###
