"""Add Mpesa tracking columns to Payment model

Revision ID: 47b78ac019fc
Revises: 819c42da9ff6
Create Date: 2025-05-26 10:45:43.488304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b78ac019fc'
down_revision = '819c42da9ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('result_desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('result_desc')
        batch_op.drop_column('result_code')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
