"""Added association tsble for brand-category management

Revision ID: 819c42da9ff6
Revises: 07b7bd3c6b15
Create Date: 2025-05-22 14:31:05.161838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819c42da9ff6'
down_revision = '07b7bd3c6b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_categories',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'category_id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('brands_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('brands_category_id_fkey', 'categories', ['category_id'], ['id'])

    op.drop_table('brand_categories')
    # ### end Alembic commands ###
