"""added 2 columns to cartitem

Revision ID: 8dacdf429d0a
Revises: d1d05f4e056b
Create Date: 2024-11-23 16:22:12.962131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dacdf429d0a'
down_revision = 'd1d05f4e056b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variation_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('variation_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('variation_price')
        batch_op.drop_column('variation_name')

    # ### end Alembic commands ###
