"""Add variation_price to order_items

Revision ID: 9924b637504a
Revises: 14136b0711ff
Create Date: 2024-12-18 19:42:58.661386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9924b637504a'
down_revision = '14136b0711ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variation_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('variation_price')

    # ### end Alembic commands ###
