"""Sign up unique values modded

Revision ID: 9f31ef3c9426
Revises: bb036d9e616d
Create Date: 2024-11-15 18:01:18.604973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f31ef3c9426'
down_revision = 'bb036d9e616d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_phone_number_key', type_='unique')
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)
        batch_op.create_unique_constraint('users_phone_number_key', ['phone_number'])

    # ### end Alembic commands ###
