"""Add camera features to tablet

Revision ID: b6eeca7df569
Revises: e548138db625
Create Date: 2024-10-19 11:46:00.558370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eeca7df569'
down_revision = 'e548138db625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_camera', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.drop_column('front_camera')

    # ### end Alembic commands ###
