"""Add camera features to tablet

Revision ID: bb036d9e616d
Revises: b6eeca7df569
Create Date: 2024-10-19 11:56:43.896132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb036d9e616d'
down_revision = 'b6eeca7df569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_camera', sa.String(length=100), nullable=False, server_default='default_front_camera_value'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.drop_column('front_camera')

    # ### end Alembic commands ###
