"""empty message

Revision ID: cb86ea8a452f
Revises: 47b78ac019fc
Create Date: 2026-01-08 14:45:29.517632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb86ea8a452f'
down_revision = '47b78ac019fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    with op.batch_alter_table('blacklist_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist_token', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estimated_delivery', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='shipments_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shipments_pkey'),
    sa.UniqueConstraint('tracking_number', name='shipments_tracking_number_key')
    )
    # ### end Alembic commands ###
