"""add created_at to blacklist_token

Revision ID: cc635def8abd
Revises: cb86ea8a452f
Create Date: 2026-02-09 10:50:15.036073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc635def8abd'
down_revision = 'cb86ea8a452f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_categories',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'category_id')
    )
    op.drop_table('shipments')
    with op.batch_alter_table('blacklist_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('brands_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('result_desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('result_desc')
        batch_op.drop_column('result_code')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('brands_category_id_fkey', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('blacklist_token', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estimated_delivery', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='shipments_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shipments_pkey'),
    sa.UniqueConstraint('tracking_number', name='shipments_tracking_number_key')
    )
    op.drop_table('brand_categories')
    # ### end Alembic commands ###
