"""Add hasVariation and isBestSeller fields to Product model

Revision ID: d1d05f4e056b
Revises: 6f7f93b07545
Create Date: 2024-11-17 14:56:44.244919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d05f4e056b'
down_revision = '6f7f93b07545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hasVariation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isBestSeller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('isBestSeller')
        batch_op.drop_column('hasVariation')

    # ### end Alembic commands ###
