"""Add product variations table

Revision ID: f05898053921
Revises: 1d9fae4918bd
Create Date: 2024-10-19 11:09:15.594689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05898053921'
down_revision = '1d9fae4918bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ram', sa.String(length=50), nullable=False),
    sa.Column('storage', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.drop_column('front_camera')
        batch_op.drop_column('main_camera')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tablets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_camera', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('front_camera', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    op.drop_table('product_variations')
    # ### end Alembic commands ###
